### ISSUE TITLE
Online demo is broken on iOS Safari/Chrome

### ISSUE THREAD

**Issue by takahirox** [takahirox/riscv-rust#115]
Maybe it includes something iOS browsers can't recognize?

**Comment by takahirox** [comment]
Error message

```
ReferenceError: Can't find variable: BigUint64Array  Module Code riscv_emu_rust_wasm.js
```

It seems JS-WASM bridge code uses BigUint64Array for Vec<u64> in Rust, but it isn't defined in iOS browser. Polyfill may be a solution, but I'm not sure if it's possible to certainly emulate unsigned int 64-bit array without BigUint64Array. It is used only for debugger, so disabling debugger in iOS would be another solution.

**Comment by IOOI-SqAR** [comment]
It is also broken on macOS Safari (tested on Version 13.1 (14609.1.20.111.8) and Safari Technology Preview (tested on Release 106 (Safari 13.2, WebKit 14610.1.12.2)). It used to work there.

**Comment by takahirox** [comment]
Thanks for the report. Mac/iOS doesn't seem to support BigUint64Array. I'm working on workaround.

**Comment by takahirox** [comment]
I added workaround in #116 and #117. I'm happy if you test on your Mac for me.

**Comment by takahirox** [comment]
@IOOI-SqAR  I added workaround in #116 and #117. I'm happy if you test on your Mac for me.

**Comment by IOOI-SqAR** [comment]
<img width="1459" alt="Bildschirmfoto 2020-05-15 um 21 55 22" src="https://user-images.githubusercontent.com/9305009/82090984-dfdac880-96f6-11ea-8fdd-59fddbde0cd1.png">

@takahirox great work, it works again!

**Comment by IOOI-SqAR** [comment]
@takahirox Should this BigUint64Array work on WebKit? If so, please file a bug report here

https://webkit.org/reporting-bugs/

Thanks!

**Comment by takahirox** [comment]
@IOOI-SqAR Thanks for the test!

> Should this BigUint64Array work on WebKit?

[According to this table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigUint64Array#Browser_compatibility), it seems expected behavior rather than a bug?

**Comment by IOOI-SqAR** [comment]
> @IOOI-SqAR Thanks for the test!
> 
> > Should this BigUint64Array work on WebKit?
> 
> [According to this table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigUint64Array#Browser_compatibility), it seems expected behavior rather than a bug?

Is it in the standards? Then Safari should support this too. I hate creating workarounds for different browser behavior or unimplemented standards!

**Comment by takahirox** [comment]
Sorry, I think I wrote poorly and was confusing. Yes, BigUint64Array should be in standard (ES Next?). I just personally distinguish "unimplemented stuff" from bug. (English isn't my first language so I'm not sure if this is right way.)

Anyways, Safari should support it. I don't like workarounds neither. Good to know that this issue is already reported.

**Comment by IOOI-SqAR** [comment]
FYI: https://bugs.webkit.org/show_bug.cgi?id=190800 seems to be fixed.
