### ISSUE TITLE
About riscv-rust and how it was made.

### ISSUE THREAD

**Issue by vmmc2** [takahirox/riscv-rust#123]
Hi, I've seen our project and really liked it. I've already studied the RISC-V architecture and done an instruction set simulator but now I want to do the whole processor emulator similar to what you did. Could you tell me how was your approach to do this? I mean, the sources that you studied to emulate the whole processor or if you studied a specific tutorial or paper because I've never done something similar to it.

**Comment by takahirox** [comment]
I have studied basic computer architecture with like https://www.amazon.com/dp/B00G4N7I2K/ or https://www.amazon.com/dp/B078MFDTX4/, and read through the instruction set and peripheral devices specification documents.

**Comment by takahirox** [comment]
Do you mind if closing?

**Comment by vmmc2** [comment]
Ohh ok. I think that now I know how to start. Just one more question before you closing: Could you explain how you made the terminal inside the browser?

**Comment by takahirox** [comment]
I used [xterm.js](https://xtermjs.org/) library. Very easy to make the terminal with it.

**Comment by vmmc2** [comment]
Oh, thank you very much. Gonna take a look at the library. Probably going to start at the project next week. Can I ask you more things (through email maybe or something similar) If I have doubts while developing my project?

**Comment by takahirox** [comment]
I would recommend to ask at somewhere forum because I have been busy so I can't promise I answer quickly. And I know there are many emulator developers.

By the way regarding the text, this book has a bunch of hints to make emulator

https://www.amazon.com/dp/1558609105
